Creating game.
Room: "test_test_room"
Parsing characters
Parsing Items
Parsing details 
Create room: "test_test_room"
Created all rooms 
worldFactory: done.
Done parsing world.
Parsing players... 
Room: "test_test_room"
Parsing characters
Parsing Items
Parsing details 
Create room: "test_test_room"
Created all rooms 
worldFactory: done.
initializing context stack.
Done.
Finished parsing!
[1;31mEvents: show room, from: startGame[0m
[1;31mshow, room[0m
[1;34mfirst[0m throwing: show|room
[1;32m ... [1;34mfirst: [1;32mevent triggered: h_show(show)[0m
[1;34mworld[0m throwing: show|room
[1;34mroom[0m throwing: show|room
[1;34mstandard[0m throwing: show|room
[1;32m ... [1;34mstandard: [1;32mevent triggered: h_ignore(show)[0m
[1;34mgame[0m throwing: show|room
[1;31mEvents: show room, from: CGame::play[0m
[1;31mshow, room[0m
[1;34mfirst[0m throwing: show|room
[1;32m ... [1;34mfirst: [1;32mevent triggered: h_show(show)[0m
[1;34mworld[0m throwing: show|room
[1;34mroom[0m throwing: show|room
[1;34mstandard[0m throwing: show|room
[1;32m ... [1;34mstandard: [1;32mevent triggered: h_ignore(show)[0m
[1;34mgame[0m throwing: show|exits
[1;31mEvents: show exits, from: CGame::play[0m
[1;31mshow, exits[0m
[1;34mfirst[0m throwing: show|exits
Calling:  show exits!

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testing.o is a Catch v2.13.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
Testadventure is starting
-------------------------------------------------------------------------------
../src/testing/test_startup.cc:11
...............................................................................

../src/testing/test_startup.cc:24: FAILED:
  REQUIRE( game.play("show exits", params->txtad_player(), online_players) != "" )
due to unexpected exception with message:
  [json.exception.type_error.306] cannot use value() with null

===============================================================================
test cases: 1 | 1 failed
assertions: 3 | 2 passed | 1 failed

